version: '3.9'

services:
  scrapyd:
    build: ./scrapyd
    container_name: scrapyd
    ports:
      - "6800:6800"
    networks:
      - scrapynet

  scrapydweb:
    build: ./scrapydweb
    container_name: scrapydweb
    ports:
      - "5015:5000"
    depends_on:
      - scrapyd
    networks:
      - scrapynet

networks:
  scrapynet:
    driver: bridge
