pipeline {
  agent any

  environment {
    REGISTRY   = 'registry.billlvtech.site'
    IMAGE_TAG  = 'latest'
  }

  stages {
    stage('Build scrapyd') {
      steps {
        sh '''
          docker build -t scrapyd ./scrapyd
          docker tag scrapyd $REGISTRY/scrapy/scrapyd:$IMAGE_TAG
        '''
      }
    }

    stage('Build scrapydweb') {
      steps {
        sh '''
          docker build -t scrapydweb ./scrapydweb
          docker tag scrapydweb $REGISTRY/scrapy/scrapydweb:$IMAGE_TAG
        '''
      }
    }

    stage('Push Images') {
      steps {
        sh '''
          docker push $REGISTRY/scrapy/scrapyd:$IMAGE_TAG
          docker push $REGISTRY/scrapy/scrapydweb:$IMAGE_TAG
        '''
      }
    }
  }
}
